"""
Stock Bot — Strategy Engine

Converts normalized trading signals into strategy decisions.
"""

from signals.models import TradingSignal
from strategies.models import StrategyDecision


def generate_strategy(signal: TradingSignal) -> StrategyDecision:
    """Convert a trading signal into a strategy decision."""

    return StrategyDecision(
        symbol=signal.symbol,
        action=signal.signal,
        confidence=signal.confidence,
        rationale=f"Signal generated by {signal.source}.",
    )
